config/routes.rb
Rails.application.routes.draw do

  get 'stores/index'
  devise_for :users
  resources :line_items
  resources :carts
  root 'stores#index'
  resources :categories
  resources :games
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/game.rb
class Game < ApplicationRecord
    mount_uploader :picture, PictureUploader
    belongs_to :category
    validates :name, presence: { message: 'não pode ser deixado em branco' }, uniqueness: { message: 'já criado'} 
    validates :price, presence: { message: 'não pode ser deixado em branco'}, numericality: {message: ':valor não aceito'}
    validates_presence_of :picture
    has_many :line_items
    before_destroy :ensure_not_referenced_by_any_line_item
    private
        def ensure_not_referenced_by_any_line_item
            if line_items.empty?
                return true
            else
                errors.add(:base, 'Line Items present')
                return false
            end
        end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
    authorize! :create, @game
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    
    @game = Game.new
    authorize! :create, @game
  end

  # GET /games/1/edit
  def edit
    authorize! :edit, @game
  end

  # POST /games
  # POST /games.json
  def create
    authorize! :create, @game
    @game = Game.new(game_params)
    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Jogo adicionado com sucesso.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    authorize! :update, @game
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Jogo atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    authorize! :destroy, @game
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Jogo removido do catálogo.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:name, :price, :category_id, :picture)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% game.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :nome %>
    <%= form.text_field :name, :class=>"form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :preço %>
    <%= form.text_field :price, :class=>"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :categoria_id %>
    <%= form.select :category_id, Category.pluck(:name, :id), :prompt => 'Selecionar' %>
    <%= link_to "Criar categoria", new_category_path %>
  </div>
  
  <div class="form-group">
  <%= form.label :"Adicione uma imagem"%>
    <%= form.file_field :picture %>
  </div>
   <br>

  <div class="actions">
    <%= form.submit "Cadastrar", :class=>'btn btn-primary'%>
  </div>
  <br>
<% end %>

app/views/games/edit.html.erb
<h1>Editar Jogo</h1>

<%= render 'form', game: @game %>

<%= link_to 'Informações', @game %> |
<%= link_to 'Voltar', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de Jogos</h1>

<table class="table">
  <thead>
    <tr>
    <th>  </th>
      <th>Nome</th>
      <th>Preço</th>
      <th>Categoria</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
      <td><%= image_tag game.picture_url, size: '200x180' if game.picture.present?  %></td>
        <td><%= link_to game.name, game %></td>
        <td>R$<%= game.price %></td>
        <td><%= game.category.name %></td>
        <% if can? :create, Game%>
        <td><%= link_to 'Editar', edit_game_path(game) %></td>
        <td><%= link_to 'Deletar', game, method: :delete, data: { confirm: 'Deseja mesmo excluir o jogo da lista?' } %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

  <% if can? :create , Game%>
    <%= link_to 'Adicionar Jogo', new_game_path %>
  <% end%>

app/views/games/new.html.erb
<h1>Cadastrar Jogo</h1>

<%= render 'form', game: @game %>

<%= link_to 'Voltar', games_path %>

app/views/games/show.html.erb
<p>
  <%= image_tag(@game.picture_url, size: '200x180') if @game.picture.present?  %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @game.name %>
</p>

<p>
  <strong>Preço:</strong>
  <%= @game.price %>
</p>

<p>
  <strong>Categoria:</strong>
  <%= @game.category.name %>
</p>
<br>
<div class="price_line" >
  <%= button_to 'Adicionar ao carrinho', line_items_path(:game_id => @game), :class=>"btn btn-primary" %>
</div>
<br>
<% if can? :edit, Game%>
  <%= link_to 'Editar', edit_game_path(@game) %> |
  <%= link_to 'Voltar', games_path %>
<% else %>
  <%= link_to 'Voltar', root_path %>
<% end%>