config/routes.rb
Rails.application.routes.draw do

  get 'stores/index'
  devise_for :users
  resources :line_items
  resources :carts
  root 'stores#index'
  resources :categories
  resources :games
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :games
    validates :name, presence: { message: 'não pode ficar em branco'} , uniqueness: { message: 'já criado'}
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
    authorize! :read, @category
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    authorize! :read, @category
  end

  # GET /categories/new
  def new
    @category = Category.new
    authorize! :create, @category
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Categoria criada com sucesso.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Categoria atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    authorize! :destroy, @category
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Categoria deletada.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, 'Nome' %>
    <%= form.text_field :name, :class=>"form-control" %>
  </div>

  <br>

  <div class="actions">
    <%= form.submit "Confirmar", :class=>"btn btn-primary"%>
  </div>

  <br>

<% end %>

app/views/categories/edit.html.erb
<h1>Editando Categoria</h1>

<%= render 'form', category: @category %>

<%= link_to 'Voltar', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categorias</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= link_to category.name, edit_category_path(category) %></td>
        <td><%= link_to 'Deletar', category, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova categoria', new_category_path %>

app/views/categories/new.html.erb
<h1>Nova Categoria</h1>

<%= render 'form', category: @category %>

<%= link_to 'Voltar', new_game_path %>     ||
<%= link_to 'Todas as categorias', categories_path %>

app/views/categories/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Editar', edit_category_path(@category) %> |
<%= link_to 'Voltar', new_game_path %>